services:
  mongo-db:
    image: mongo:8.0.6
    container_name: mongo-db
    env_file: '.env'
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    networks:
      - messenger-network

  messenger-server:
    build:
      context: messenger-server
    container_name: messenger-server
    env_file: '.env'
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
    depends_on:
      - mongo-db
    networks:
      - messenger-network


  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - messenger-ui
    networks:
      - messenger-network

  messenger-ui:
    image: artem20fedorov00/messenger-ui
    container_name: messenger-ui
    depends_on:
      - messenger-server
    networks:
      - messenger-network

networks:
  messenger-network:

volumes:
  mongo: { }