services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.1
    ports:
      - '9090:8080'
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: artem
      DB_PASSWORD: q
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm/messenger.json:/opt/keycloak/data/import/messenger.json
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=artem
      - MONGO_INITDB_ROOT_PASSWORD=q
volumes:
  mongo: {}