services:
  mongo-db:
    image: mongo:8.0.6
    container_name: mongo-db
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - messenger-network

  messenger-server:
    image: artem20fedorov00/messenger-server
    container_name: messenger-server
    depends_on:
      - mongo-db
    networks:
      - messenger-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - messenger-ui
    networks:
      - messenger-network

  messenger-ui:
    image: artem20fedorov00/messenger-ui
    container_name: messenger-ui
    depends_on:
      - messenger-server
    networks:
      - messenger-network

networks:
  messenger-network:

volumes:
  mongo: { }