name: messenger
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: messenger
    networks:
      - messenger-network
  server:
    restart: always
    build:
      dockerfile: ./messenger-server/Dockerfile
      args:
        JAR_FILE: messenger-server/target/messenger-server-0.0.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    networks:
      - messenger-network
  ui:
    restart: always
    build:
      context: ./messenger-ui
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - messenger-network
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - ui
    networks:
      - messenger-network
networks:
  messenger-network: