services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.1
    ports:
      - '9090:8080'
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: artem
      DB_PASSWORD: q
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/standalone/configuration/messenger.json
    volumes:
      - ./keycloak/realm/messenger.json:/opt/jboss/keycloak/standalone/configuration/messenger.json