spring:
  data:
    mongodb:
      username: user
      password: q
      host: localhost
      port: 27017
      database: messenger
      authentication-database: admin
      auto-index-creation: true