spring:
  data:
    mongodb:
      username: artem
      password: q
      host: localhost
      port: 27017
      database: messenger
      authentication-database: admin
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/messenger"
allowed-origins: http://localhost:3000, http://localhost:9090

