name: Deploy Messenger Server

on:
  push:
    branches: [ master ]
    paths:
      - messenger-server/**
      - 'docker-compose.yml'
      - .github/workflows/*-messenger-server.yml
jobs:
  test:
    name: Run Unit/Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Running Tests
        run: |
          cd messenger-server
          mvn clean verify

  build:
    runs-on: ubuntu-latest
    name: Build Messenger Server
    needs: [ test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Compile project
        run: |
          cd messenger-server
          mvn clean package -DskipTests

  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Extract project version
        id: extract_version
        run: |
          cd messenger-server
          echo "VERSION=$( mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression="project.version" -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Compile project
        run: |
          cd messenger-server
          mvn clean package

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: messenger-server
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/messenger-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/messenger-server:${{ steps.extract_version.outputs.VERSION }}
          build-args: |
            JAR_FILE=target/messenger-server-${{ steps.extract_version.outputs.VERSION }}-exec.jar

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: [ build-image ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Create deployment folder
        run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p messenger-app"

      - name: Copy docker-compose file
        run: |
          cd config/prod
          scp docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:messenger-app/docker-compose.yml

      - name: Deploy Application to VPS
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
           cd messenger-app
           docker compose -f docker-compose.yml pull -q
           docker compose -f docker-compose.yml up -d
          EOF